task 0 update

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,14 +1,25 @@
 #!/usr/bin/env bash
-# This script transfers a file from Holberton's client to another.
-# Accepts four arguments:
-#+    The path to the file to be transferred.
-#+    The IP of the server to transfer the file to.
-#+    The username that scp connects with.
-#+    The path to the SSH private key that scp uses.
+# Script Name: 0-transfer_file
+# Description: Transfer a file from client to server using scp
 
-if [ $# -lt 4 ]
-then
-  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+# Check if all 4 parameters are provided
+if [ "$#" -ne 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assign parameters to variables
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key="$4"
+
+# Transfer the file using scp
+scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~/
+
+# Check the exit status of scp command
+if [ $? -eq 0 ]; then
+    echo "File successfully transferred to $username@$server_ip:~/"
 else
-  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
+    echo "Error transferring file. Check the parameters and try again."
 fi
