task 7 update

diff --git a/0x1A-application_server/4-reload_gunicorn_no_downtime b/0x1A-application_server/4-reload_gunicorn_no_downtime
--- a/0x1A-application_server/4-reload_gunicorn_no_downtime
+++ b/0x1A-application_server/4-reload_gunicorn_no_downtime
@@ -1,4 +1,13 @@
 #!/usr/bin/env bash
-# Gracefully reloads Gunicorn.
+# This script reloads Gunicorn gracefully
 
-ps aux | grep gunicorn | awk '{ print $2 }' | xargs kill -HUP
+# Check if Gunicorn is running
+if ! pgrep -f "gunicorn" > /dev/null; then
+    echo "Gunicorn master process not found. Is Gunicorn running?"
+    exit 1
+fi
+
+# Reload Gunicorn gracefully
+kill -HUP $(pgrep -f "gunicorn")
+
+echo "Gunicorn reloaded gracefully."
